version: "3"

volumes:
  shadowmere_data:
  redis_data:


services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - shadowmere_data:/var/lib/postgresql/data
    env_file:
      - .env

  shadowmere:
    image: guamulo/shadowmere
    restart: always
    build:
      context: .
    volumes:
      - .:/home
    working_dir: /home/shadowmere
    command: /start.sh
    entrypoint: /entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"
      - "8002-8007:8002-8007"

  celery:
    image: guamulo/shadowmere
    restart: always
    volumes:
      - .:/home
    working_dir: /home/shadowmere
    command: celery -A shadowmere worker -l info
    env_file:
      - .env
    depends_on:
      - shadowmere
      - redis

  celery-beat:
    image: guamulo/shadowmere
    restart: always
    volumes:
      - .:/home
    working_dir: /home/shadowmere
    command: celery -A shadowmere beat -l info
    env_file:
      - .env
    depends_on:
      - shadowmere
      - redis
