name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
        env:
          DEBUG: True
          SECRET_KEY: whatever
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl --fail -H "Authorization: ${{ secrets.DEPLOY_TOKEN }}" "https://smd.akiel.dev/hook?script=${{ secrets.DEPLOY_SCRIPT }}"
      - name: Send slack notification
        uses: Gamesight/slack-workflow-status@master
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: 'shadowmere'
          name: 'Deployment'
      - name: Track release in sentry
        run: |
          curl https://sentry.io/api/hooks/release/builtin/${{ secrets.SENTRY_RELEASE_TRACKING }}/ \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"version": "${{ github.sha }}"}'
